<?php

namespace Fango\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TotalReachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotalReachRepository extends EntityRepository
{
}
