<?php

namespace Seferov\CrawlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TwitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterRepository extends EntityRepository
{
}
